# Generated by Django 2.2 on 2020-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20201023_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gsttot',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tot_amount',
            field=models.FloatField(null=True),
        ),
    ]
